apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: back
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx4
  labels:
    app: back
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:alpine