apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: cont1
    image: nginx:alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
  - name: cont1
    image: nginx:alpine